from fpdf import FPDF
from datetime import date
import streamlit as st

_RISK_RANK = {"LOW": 0, "MEDIUM": 1, "HIGH": 2}

_RISK_RGB = {
    "HIGH":   (220, 38,  38),   # #DC2626 Vibrant Red
    "MEDIUM": (217, 119,  6),   # #D97706 Compliance Gold
    "LOW":    (22,  163, 74),   # #16A34A Forest Green
}

# Unicode typographic chars that Helvetica (latin-1) cannot encode.
# The AI commonly generates all of these.
_CHAR_MAP = str.maketrans({
    "—": " - ",   # em dash          —
    "–": " - ",   # en dash          –
    "‘": "'",     # left single quote '
    "’": "'",     # right single quote '
    "“": '"',     # left double quote "
    "”": '"',     # right double quote "
    "…": "...",   # ellipsis          …
    "•": "-",     # bullet            •
    " ": " ",     # non-breaking space
})


def _sanitize(text: str) -> str:
    """Replace Unicode typographic chars with latin-1 equivalents, then
    encode/decode as a safety net for any remaining non-latin-1 codepoints."""
    return text.translate(_CHAR_MAP).encode("latin-1", "replace").decode("latin-1")


class _ReportPDF(FPDF):
    """Pins a footer on every page via the FPDF footer() hook,
    which prevents blank trailing pages caused by flowing content."""

    def __init__(self, scan_date: str):
        super().__init__()
        self._scan_date = scan_date

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "", 7)
        self.set_text_color(148, 163, 184)
        self.cell(
            0, 5,
            f"Generated by Compliance Lite  -  {self._scan_date}  -  Confidential",
            align="C",
        )


def create_compliance_report(scan_result: dict) -> bytes:
    user_email = _sanitize(st.session_state.get("user_email") or "N/A")

    files     = scan_result.get("files", [])
    total_phi = sum(f["phi_count"] for f in files)
    scan_date = date.today().strftime("%B %d, %Y")

    # Batch risk = maximum risk level across all files
    batch_risk = max(
        (f["risk"] for f in files),
        key=lambda r: _RISK_RANK.get(r, 0),
        default="LOW",
    )
    # Weighted compliance score: clean files / total files × 100
    total_files    = len(files)
    files_with_phi = sum(1 for f in files if f.get("phi_count", 0) > 0)
    score_pct      = int(round((total_files - files_with_phi) / total_files * 100)) if total_files else 100
    comp_score     = f"{score_pct}%"

    pdf = _ReportPDF(scan_date)
    # margin=15 leaves 15 mm clearance before triggering a page break,
    # which is enough for the footer without creating a spurious blank page.
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(20, 20, 20)
    pdf.add_page()

    # ── Header bar (navy — do not alter) ───────────────────────────────────
    pdf.set_fill_color(10, 22, 40)
    pdf.rect(0, 0, 210, 44, style="F")
    pdf.set_y(9)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(248, 250, 252)
    pdf.cell(0, 12, "Compliance Lite", ln=True, align="C")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(148, 163, 184)
    pdf.cell(0, 7, "Enterprise PHI Detection  -  Compliance Assessment Report", ln=True, align="C")
    pdf.set_fill_color(59, 130, 246)
    pdf.rect(0, 44, 210, 2, style="F")

    pdf.ln(18)

    # ── Meta block ──────────────────────────────────────────────────────────
    pdf.set_fill_color(241, 245, 249)
    pdf.rect(20, pdf.get_y(), 170, 28, style="F")
    pdf.set_x(25)

    def meta_row(label, value):
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(38, 7, label.upper(), ln=False)
        pdf.set_font("Helvetica", "", 8)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(0, 7, _sanitize(value), ln=True)
        pdf.set_x(25)

    meta_row("Operator",  "Katie Gray")
    meta_row("Role",      "Marketing & UX Lead")
    meta_row("Account",   user_email)
    meta_row("Scan Date", scan_date)

    pdf.ln(8)

    # ── Section heading helper ───────────────────────────────────────────────
    def section_heading(title: str):
        pdf.set_fill_color(10, 22, 40)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 9, f"  {title}", ln=True, fill=True)
        pdf.ln(3)
        pdf.set_text_color(15, 23, 42)

    # ── Executive Summary TABLE ──────────────────────────────────────────────
    section_heading("Executive Summary")

    COL_LABEL = 80
    COL_VALUE = 90
    ROW_H     = 8

    def tbl_header(label, value):
        pdf.set_fill_color(30, 41, 59)
        pdf.set_draw_color(203, 213, 225)
        pdf.set_font("Helvetica", "B", 8.5)
        pdf.set_text_color(248, 250, 252)
        pdf.cell(COL_LABEL, ROW_H, f"  {label}", border=1, ln=False, fill=True)
        pdf.cell(COL_VALUE, ROW_H, f"  {value}", border=1, ln=True, fill=True)

    def tbl_row(label, value, value_rgb=None):
        pdf.set_fill_color(255, 255, 255)
        pdf.set_draw_color(203, 213, 225)
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(71, 85, 105)
        pdf.cell(COL_LABEL, ROW_H, f"  {label}", border=1, ln=False, fill=True)
        if value_rgb:
            pdf.set_text_color(*value_rgb)
            pdf.set_font("Helvetica", "B", 8.5)
        else:
            pdf.set_text_color(15, 23, 42)
        pdf.cell(COL_VALUE, ROW_H, f"  {value}", border=1, ln=True, fill=True)

    tbl_header("Metric", "Value")
    tbl_row("Compliance Score", comp_score)
    tbl_row("Risk Level", batch_risk, value_rgb=_RISK_RGB[batch_risk])
    tbl_row("Total PII / PHI Findings", f"{total_phi} item(s)")
    tbl_row("Files Processed", str(scan_result.get("count", len(files))))

    pdf.ln(7)

    # ── Per-file Results ─────────────────────────────────────────────────────
    section_heading("File-by-File Results")

    last_idx = len(files) - 1
    for idx, fd in enumerate(files):
        risk       = fd.get("risk", "LOW")
        badge_rgb  = _RISK_RGB[risk]
        badge_text = f" {risk} RISK "
        badge_w    = 32 if risk == "MEDIUM" else 24

        # Risk badge + filename row
        pdf.set_fill_color(*badge_rgb)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(badge_w, 6, badge_text, ln=False, fill=True)
        pdf.set_fill_color(241, 245, 249)
        pdf.set_text_color(15, 23, 42)
        pdf.set_font("Helvetica", "", 8)
        pdf.cell(0, 6, f"  {_sanitize(fd['name'])}", ln=True, fill=True)

        # PHI breakdown line — bold, pipe-separated for scannability
        pdf.set_font("Helvetica", "B", 8)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(badge_w, 5, "", ln=False)
        detail = (
            f"PHI items detected: {fd['phi_count']}"
            f"  |  Phones: {fd.get('phone_count', 0)}"
            f"  |  Emails: {fd.get('email_count', 0)}"
        )
        pdf.cell(0, 5, detail, ln=True)
        pdf.ln(1)   # consistent 1 mm gap before the Insight block

        # Compliance Insight — Helvetica Roman, deep charcoal #1a202c
        insight = fd.get("risk_summary") or ""
        if insight:
            pdf.set_font("Helvetica", "", 7.5)
            pdf.set_text_color(26, 32, 44)
            pdf.cell(badge_w, 5, "", ln=False)
            pdf.multi_cell(0, 5, f"Insight: {_sanitize(insight)}")

        # Gap between file entries only — omitted after the last file so the
        # cursor never drifts past the auto-page-break margin into a blank page.
        # The _ReportPDF.footer() hook is called by fpdf2's output() engine and
        # cannot itself create a new page, so the footer is always safe.
        if idx < last_idx:
            pdf.ln(3)

    return bytes(pdf.output())
